# Generated by Django 3.1.2 on 2021-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210729_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение категории товаров'),
            preserve_default=False,
        ),
    ]
